name = "trickpal"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"

[build.upload]
format = "directory"

[site]
bucket = "./out"
pages_build_output_dir = "out"

[env.production]
workers_dev = true 